base_url = "https://maxarvid.com"
theme = "d3c3nt"

[extra]
d3_icon = "/favicon.png"
d3_nav = [
  { name = "home", path = "/" },
  { name = "posts", path = "/posts/" },
  { name = "about", path = "/about/"}
]