base_url = "https://maxarvid.com"
title = "maxarvid"
compile_sass = true
build_search_index = false

theme = "oceanic-zen"

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
author = "maxarvid"
github = "maxarvid"